import { PilotManualCheckType } from '@prisma/client';

export const PILOT_SOURCE = 'PILOT_CONTROL';

export const PILOT_EVENT = {
  COHORT_CREATED: 'PILOT_COHORT_CREATED',
  PARTICIPANT_ADDED: 'PILOT_PARTICIPANT_ADDED',
  PARTICIPANT_ACTIVATED: 'PILOT_PARTICIPANT_ACTIVATED',
  COHORT_COMPLETED: 'PILOT_COHORT_COMPLETED',
  GO_STATUS_CHANGED: 'PILOT_GO_STATUS_CHANGED',
  REPORT_GENERATED: 'PILOT_REPORT_GENERATED',
} as const;

export const PILOT_SMOKE_EVENT = {
  STARTED: 'SMOKE_TEST_STARTED',
  PASSED: 'SMOKE_TEST_PASSED',
  FAILED: 'SMOKE_TEST_FAILED',
} as const;

export const REQUIRED_PILOT_CHECKS = Object.values(PilotManualCheckType);
