export const AUDIT_ACTION = {
  LOGIN: 'LOGIN',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_CANCELED: 'SUBSCRIPTION_CANCELED',
  SUBSCRIPTION_CANCELLATION_SCHEDULED: 'SUBSCRIPTION_CANCELLATION_SCHEDULED',
  WORKOUT_GENERATED: 'WORKOUT_GENERATED',
  DIET_GENERATED: 'DIET_GENERATED',
  NUTRITION_ANALYSIS_COMPLETED: 'NUTRITION_ANALYSIS_COMPLETED',
} as const;

export const AUDIT_ENTITY = {
  USER: 'USER',
  PAYMENT: 'PAYMENT',
  SUBSCRIPTION: 'SUBSCRIPTION',
  WORKOUT_PLAN: 'WORKOUT_PLAN',
  DIET_PLAN: 'DIET_PLAN',
  MEAL_ANALYSIS: 'MEAL_ANALYSIS',
} as const;
