version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: singulfit-postgres
    restart: always
    environment:
      POSTGRES_DB: singulfit
      POSTGRES_USER: singulfit
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - singulfit_pgdata:/var/lib/postgresql/data

volumes:
  singulfit_pgdata:
