export const INTERNAL_EVENT = {
  PAGBANK_WEBHOOK_RECEIVED: 'PAGBANK_WEBHOOK_RECEIVED',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  WHATSAPP_MESSAGE_RECEIVED: 'WHATSAPP_MESSAGE_RECEIVED',
  MEDIA_RECEIVED: 'MEDIA_RECEIVED',
  NUTRITION_ANALYSIS_COMPLETED: 'NUTRITION_ANALYSIS_COMPLETED',
  AI_RESPONSE_GENERATED: 'AI_RESPONSE_GENERATED',
  OUTBOUND_MESSAGE_REQUESTED: 'OUTBOUND_MESSAGE_REQUESTED',
  AUTOMATION_TRIGGERED: 'AUTOMATION_TRIGGERED',
  USER_CONTEXT_REFRESH_REQUESTED: 'USER_CONTEXT_REFRESH_REQUESTED',
  USER_CONTEXT_REFRESH_COMPLETED: 'USER_CONTEXT_REFRESH_COMPLETED',
  USER_CONTEXT_REFRESH_FAILED: 'USER_CONTEXT_REFRESH_FAILED',
} as const;

export type InternalEventType =
  (typeof INTERNAL_EVENT)[keyof typeof INTERNAL_EVENT];

export const OUTBOX_SOURCE = 'OUTBOX';

export const OUTBOX_SYSTEM_EVENT = {
  RETRY_SCHEDULED: 'RETRY_SCHEDULED',
  RETRY_EXECUTED: 'RETRY_EXECUTED',
  DEAD_LETTER: 'DEAD_LETTER',
  LEASE_EXPIRED: 'LEASE_EXPIRED',
  EVENT_RECOVERED: 'EVENT_RECOVERED',
  EVENT_IGNORED: 'EVENT_IGNORED',
} as const;

export const WORKER_NAME = {
  OUTBOX: 'OUTBOX_WORKER',
  AI: 'AI_WORKER',
  AUTOMATION: 'AUTOMATION_WORKER',
} as const;

export type WorkerName = (typeof WORKER_NAME)[keyof typeof WORKER_NAME];

export const WORKER_EVENT_TYPES: Record<WorkerName, readonly string[]> = {
  [WORKER_NAME.OUTBOX]: [
    INTERNAL_EVENT.PAGBANK_WEBHOOK_RECEIVED,
    INTERNAL_EVENT.PAYMENT_APPROVED,
    INTERNAL_EVENT.SUBSCRIPTION_ACTIVATED,
    INTERNAL_EVENT.WHATSAPP_MESSAGE_RECEIVED,
    INTERNAL_EVENT.OUTBOUND_MESSAGE_REQUESTED,
    INTERNAL_EVENT.USER_CONTEXT_REFRESH_REQUESTED,
    INTERNAL_EVENT.USER_CONTEXT_REFRESH_COMPLETED,
    INTERNAL_EVENT.USER_CONTEXT_REFRESH_FAILED,
  ],
  [WORKER_NAME.AI]: [
    INTERNAL_EVENT.MEDIA_RECEIVED,
    INTERNAL_EVENT.NUTRITION_ANALYSIS_COMPLETED,
    INTERNAL_EVENT.AI_RESPONSE_GENERATED,
  ],
  [WORKER_NAME.AUTOMATION]: [INTERNAL_EVENT.AUTOMATION_TRIGGERED],
};
