export const CONTEXT_SOURCE = 'CONTEXT';

export const CONTEXT_AGGREGATE = {
  REFRESH: 'USER_CONTEXT_REFRESH',
} as const;

export const CONTEXT_MEMORY_SOURCE = {
  CONSOLIDATED: 'CONSOLIDATED',
} as const;

export const CONTEXT_AUDIT_ACTION = {
  REFRESH_STARTED: 'USER_CONTEXT_REFRESH_STARTED',
  REFRESH_COMPLETED: 'USER_CONTEXT_REFRESH_COMPLETED',
  REFRESH_FAILED: 'USER_CONTEXT_REFRESH_FAILED',
} as const;

export const CONTEXT_AUDIT_ENTITY = {
  USER_CONTEXT: 'USER_CONTEXT',
} as const;
