export const IMAGE_ANALYSIS_DAILY = 'IMAGE_ANALYSIS_DAILY';
export const IMAGE_ANALYSIS_MONTHLY = 'IMAGE_ANALYSIS_MONTHLY';
export const IMAGE_ANALYSIS = 'IMAGE_ANALYSIS';
export const NUTRITION_PLAN_GENERATION = 'NUTRITION_PLAN_GENERATION';
export const WORKOUT_PLAN_GENERATION = 'WORKOUT_PLAN_GENERATION';

export const COMMERCIAL_USAGE_ENTITLEMENTS = [
  NUTRITION_PLAN_GENERATION,
  WORKOUT_PLAN_GENERATION,
  IMAGE_ANALYSIS,
] as const;

export type CommercialUsageEntitlementCode =
  (typeof COMMERCIAL_USAGE_ENTITLEMENTS)[number];

export const IMAGE_ANALYSIS_ENTITLEMENTS = [
  IMAGE_ANALYSIS_DAILY,
  IMAGE_ANALYSIS_MONTHLY,
] as const;

export type ImageAnalysisEntitlementCode =
  (typeof IMAGE_ANALYSIS_ENTITLEMENTS)[number];
